/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PlayingCardsRouteImport } from './routes/playing-cards'
import { Route as AssetsIndexRouteImport } from './routes/assets.index'
import { Route as AssetsMissionsRouteImport } from './routes/assets.missions'
import { Route as AssetsPlayingCardsRouteImport } from './routes/assets.playing-cards'
import { Route as LobbyCodeRouteImport } from './routes/lobby.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayingCardsRoute = PlayingCardsRouteImport.update({
  id: '/playing-cards',
  path: '/playing-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsMissionsRoute = AssetsMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsPlayingCardsRoute = AssetsPlayingCardsRouteImport.update({
  id: '/playing-cards',
  path: '/playing-cards',
  getParentRoute: () => AssetsRoute,
} as any)
const LobbyCodeRoute = LobbyCodeRouteImport.update({
  id: '/lobby/$code',
  path: '/lobby/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/campaign': typeof CampaignRoute
  '/missions': typeof MissionsRoute
  '/play': typeof PlayRoute
  '/playing-cards': typeof PlayingCardsRoute
  '/assets/missions': typeof AssetsMissionsRoute
  '/assets/playing-cards': typeof AssetsPlayingCardsRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/assets/': typeof AssetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/missions': typeof MissionsRoute
  '/play': typeof PlayRoute
  '/playing-cards': typeof PlayingCardsRoute
  '/assets/missions': typeof AssetsMissionsRoute
  '/assets/playing-cards': typeof AssetsPlayingCardsRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/assets': typeof AssetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/campaign': typeof CampaignRoute
  '/missions': typeof MissionsRoute
  '/play': typeof PlayRoute
  '/playing-cards': typeof PlayingCardsRoute
  '/assets/missions': typeof AssetsMissionsRoute
  '/assets/playing-cards': typeof AssetsPlayingCardsRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/assets/': typeof AssetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/campaign'
    | '/missions'
    | '/play'
    | '/playing-cards'
    | '/assets/missions'
    | '/assets/playing-cards'
    | '/lobby/$code'
    | '/assets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaign'
    | '/missions'
    | '/play'
    | '/playing-cards'
    | '/assets/missions'
    | '/assets/playing-cards'
    | '/lobby/$code'
    | '/assets'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/campaign'
    | '/missions'
    | '/play'
    | '/playing-cards'
    | '/assets/missions'
    | '/assets/playing-cards'
    | '/lobby/$code'
    | '/assets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRouteWithChildren
  CampaignRoute: typeof CampaignRoute
  MissionsRoute: typeof MissionsRoute
  PlayRoute: typeof PlayRoute
  PlayingCardsRoute: typeof PlayingCardsRoute
  LobbyCodeRoute: typeof LobbyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playing-cards': {
      id: '/playing-cards'
      path: '/playing-cards'
      fullPath: '/playing-cards'
      preLoaderRoute: typeof PlayingCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/missions': {
      id: '/assets/missions'
      path: '/missions'
      fullPath: '/assets/missions'
      preLoaderRoute: typeof AssetsMissionsRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/playing-cards': {
      id: '/assets/playing-cards'
      path: '/playing-cards'
      fullPath: '/assets/playing-cards'
      preLoaderRoute: typeof AssetsPlayingCardsRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/lobby/$code': {
      id: '/lobby/$code'
      path: '/lobby/$code'
      fullPath: '/lobby/$code'
      preLoaderRoute: typeof LobbyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssetsRouteChildren {
  AssetsMissionsRoute: typeof AssetsMissionsRoute
  AssetsPlayingCardsRoute: typeof AssetsPlayingCardsRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsMissionsRoute: AssetsMissionsRoute,
  AssetsPlayingCardsRoute: AssetsPlayingCardsRoute,
  AssetsIndexRoute: AssetsIndexRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRouteWithChildren,
  CampaignRoute: CampaignRoute,
  MissionsRoute: MissionsRoute,
  PlayRoute: PlayRoute,
  PlayingCardsRoute: PlayingCardsRoute,
  LobbyCodeRoute: LobbyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
