/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PlayingCardsRouteImport } from './routes/playing-cards'
import { Route as AssetsIndexRouteImport } from './routes/assets.index'
import { Route as AssetsMissionsRouteImport } from './routes/assets.missions'
import { Route as AssetsPlayingCardsRouteImport } from './routes/assets.playing-cards'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as HistoryAttemptIdRouteImport } from './routes/history.$attemptId'
import { Route as LobbyCodeRouteImport } from './routes/lobby.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayingCardsRoute = PlayingCardsRouteImport.update({
  id: '/playing-cards',
  path: '/playing-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsMissionsRoute = AssetsMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsPlayingCardsRoute = AssetsPlayingCardsRouteImport.update({
  id: '/playing-cards',
  path: '/playing-cards',
  getParentRoute: () => AssetsRoute,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HistoryRoute,
} as any)
const HistoryAttemptIdRoute = HistoryAttemptIdRouteImport.update({
  id: '/$attemptId',
  path: '/$attemptId',
  getParentRoute: () => HistoryRoute,
} as any)
const LobbyCodeRoute = LobbyCodeRouteImport.update({
  id: '/lobby/$code',
  path: '/lobby/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/history': typeof HistoryRouteWithChildren
  '/missions': typeof MissionsRoute
  '/play': typeof PlayRoute
  '/playing-cards': typeof PlayingCardsRoute
  '/assets/missions': typeof AssetsMissionsRoute
  '/assets/playing-cards': typeof AssetsPlayingCardsRoute
  '/history/$attemptId': typeof HistoryAttemptIdRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/assets/': typeof AssetsIndexRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/missions': typeof MissionsRoute
  '/play': typeof PlayRoute
  '/playing-cards': typeof PlayingCardsRoute
  '/assets/missions': typeof AssetsMissionsRoute
  '/assets/playing-cards': typeof AssetsPlayingCardsRoute
  '/history/$attemptId': typeof HistoryAttemptIdRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/assets': typeof AssetsIndexRoute
  '/history': typeof HistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/history': typeof HistoryRouteWithChildren
  '/missions': typeof MissionsRoute
  '/play': typeof PlayRoute
  '/playing-cards': typeof PlayingCardsRoute
  '/assets/missions': typeof AssetsMissionsRoute
  '/assets/playing-cards': typeof AssetsPlayingCardsRoute
  '/history/$attemptId': typeof HistoryAttemptIdRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/assets/': typeof AssetsIndexRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/history'
    | '/missions'
    | '/play'
    | '/playing-cards'
    | '/assets/missions'
    | '/assets/playing-cards'
    | '/history/$attemptId'
    | '/lobby/$code'
    | '/assets/'
    | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/missions'
    | '/play'
    | '/playing-cards'
    | '/assets/missions'
    | '/assets/playing-cards'
    | '/history/$attemptId'
    | '/lobby/$code'
    | '/assets'
    | '/history'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/history'
    | '/missions'
    | '/play'
    | '/playing-cards'
    | '/assets/missions'
    | '/assets/playing-cards'
    | '/history/$attemptId'
    | '/lobby/$code'
    | '/assets/'
    | '/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRouteWithChildren
  HistoryRoute: typeof HistoryRouteWithChildren
  MissionsRoute: typeof MissionsRoute
  PlayRoute: typeof PlayRoute
  PlayingCardsRoute: typeof PlayingCardsRoute
  LobbyCodeRoute: typeof LobbyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playing-cards': {
      id: '/playing-cards'
      path: '/playing-cards'
      fullPath: '/playing-cards'
      preLoaderRoute: typeof PlayingCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/missions': {
      id: '/assets/missions'
      path: '/missions'
      fullPath: '/assets/missions'
      preLoaderRoute: typeof AssetsMissionsRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/playing-cards': {
      id: '/assets/playing-cards'
      path: '/playing-cards'
      fullPath: '/assets/playing-cards'
      preLoaderRoute: typeof AssetsPlayingCardsRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/history/': {
      id: '/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/history/$attemptId': {
      id: '/history/$attemptId'
      path: '/$attemptId'
      fullPath: '/history/$attemptId'
      preLoaderRoute: typeof HistoryAttemptIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/lobby/$code': {
      id: '/lobby/$code'
      path: '/lobby/$code'
      fullPath: '/lobby/$code'
      preLoaderRoute: typeof LobbyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssetsRouteChildren {
  AssetsMissionsRoute: typeof AssetsMissionsRoute
  AssetsPlayingCardsRoute: typeof AssetsPlayingCardsRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsMissionsRoute: AssetsMissionsRoute,
  AssetsPlayingCardsRoute: AssetsPlayingCardsRoute,
  AssetsIndexRoute: AssetsIndexRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

interface HistoryRouteChildren {
  HistoryAttemptIdRoute: typeof HistoryAttemptIdRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryAttemptIdRoute: HistoryAttemptIdRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRouteWithChildren,
  HistoryRoute: HistoryRouteWithChildren,
  MissionsRoute: MissionsRoute,
  PlayRoute: PlayRoute,
  PlayingCardsRoute: PlayingCardsRoute,
  LobbyCodeRoute: LobbyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
